website/models/task.py
from .. import db
from ..models.user import User
from sqlalchemy import ForeignKey
import datetime


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True, unique=True)
    user_id = db.Column(db.Integer, ForeignKey('user.id'))
    task_desc = db.Column(db.String(100))
    task_date = db.Column(db.String(20))
    status = db.Column(db.String(20))

    def __init__(self, user_id, task_desc):
        """
        constructor
        :param user_id: string
        :param task_desc: strings
        :param task_date: string
        :param task_time: string
        """
        self.user_id = user_id
        self.task_desc = task_desc
        self.task_date = datetime.datetime.now().strftime('%d/ %m/ %Y - %H:%M')
        self.status = 'Open'

    def __repr__(self) -> str:
        return f'{self.task_desc} - {self.task_date}'

    def get_status(self):
        return self.status

    def change_completed(self):
        self.status = 'Completed'

    def change_trashed(self):
        self.status = 'Trashed'

    def delete_task(self):
        self.status = 'Deleted'

website/models/user.py
from .. import db
from sqlalchemy.orm import relationship
from flask_login import UserMixin
from werkzeug.security import generate_password_hash


class User(db.Model, UserMixin):

    id = db.Column(db.Integer, primary_key=True, unique=True)  # primary key is id
    admin = db.Column(db.String(5))  # if user is an admin
    fullname = db.Column(db.String(50))  # fullname of user
    email = db.Column(db.String(50), unique=True)  # email of user is unique
    password = db.Column(db.String(50))  # password of user
    status = db.Column(db.String(10))  # status of user (Active / Deleted)
    tasks = db.relationship('Task', primaryjoin='User.id == Task.user_id')

    def __init__(self, fullname, email, password):
        """
        constructor
        :param fullname: String
        :param email: String
        :param password: String
        """
        self.admin = 'False'  # initially user are not admin
        self.fullname = fullname
        self.email = email
        self.password = generate_password_hash(password, 'sha256')  # password is stored as hash
        self.status = 'Active'  # initially all users will be considered active

    def get_current_tasks(self):
        tasks = []
        try:
            tasks = [task for task in self.tasks if task.get_status() == 'Open']
        except:
            pass
        return tasks
    
    def get_trashed_tasks(self):
        tasks = []
        try:
            tasks = [task for task in self.tasks if task.get_status() == 'Trashed']
        except:
            pass
        return tasks
    
    def get_completed_tasks(self):
        tasks = []
        try:
            tasks = [task for task in self.tasks if task.get_status() == 'Completed']
        except:
            pass
        return tasks

website/__init__.py
from flask import Flask, Blueprint
from flask_login import LoginManager, login_manager
from os import path
from flask_sqlalchemy import SQLAlchemy


DB_NAME = 'database.db'
db = SQLAlchemy()


def create_app(config_filename):
    app = Flask(__name__)
    
    app.config.from_pyfile(config_filename)

    db.init_app(app=app)
    create_db(app=app)

    from .views.index import index
    from .views.dashboard import dashboard
    from .auth.register import register
    from .auth.login import login


    app.register_blueprint(index, url_prefix='/')
    app.register_blueprint(register, url_prefix='/')
    app.register_blueprint(login, url_prefix='/')
    app.register_blueprint(dashboard, url_prefix='/')

    loginManager = LoginManager()
    loginManager.login_view = 'login.login_page'
    loginManager.init_app(app=app)

    from .models.user import User

    @loginManager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app


def create_db(app):
    if not path.exists(DB_NAME):
        from .models.user import User
        from .models.task import Task
        db.create_all(app=app)

website/views/dashboard.py
from flask import Blueprint, redirect, url_for, request, render_template, flash, json, jsonify
from flask_login import current_user, login_required
from ..models.task import Task
from .. import db


dashboard = Blueprint('dashboard', __name__)

@dashboard.route('/dashboard/', methods=['POST', 'GET'])
@login_required
def dashboard_page():
    if not current_user.is_authenticated or not current_user:
        flash('User is not authorized to use that page')
        return redirect(url_for('dashboard.dashboard_page'))
    current_tasks = current_user.get_current_tasks()
    completed_tasks = current_user.get_completed_tasks()
    trashed_tasks = current_user.get_trashed_tasks()
    return render_template('dashboard.html', user=current_user, current_tasks=current_tasks, completed_tasks=completed_tasks, trashed_tasks=trashed_tasks, time='9:00 AM')

@dashboard.route('/manage_task/', methods=['POST'])
@login_required
def manage_task():
    if not current_user.is_authenticated:
        flash('User is not authorized to use that action')
        return redirect(url_for('dashboard.dashboard_page'))
    task_id = json.loads(request.data)['taskId']
    task = Task.query.filter_by(id=task_id).first()
    if task:
        current_status = task.get_status()
        if current_status == 'Open':
            task.change_completed()
        elif current_status == 'Completed':
            task.change_trashed()
        else:
            task.delete_task()
        db.session.commit()
    return jsonify({})

@dashboard.route('/add_task/', methods=['POST'])
@login_required
def add_task():
    if not current_user.is_authenticated:
        flash('User is not authorized to use that action')
        return redirect(url_for('dashboard.dashboard_page'))
    new_task_desc = json.loads(request.data)['task']
    if len(new_task_desc) > 2:
        try:
            new_task = Task(current_user.id, new_task_desc)
            db.session.add(new_task)
            db.session.commit()
            flash('Task added')
        except:
            flash('Internal server error', category='danger')
    return jsonify({})

website/views/index.py
from flask import Blueprint, render_template, url_for, redirect


index = Blueprint('index', __name__)


@index.route('/')
@index.route('/index/')
def index_page():
    return render_template('index.html', current_page='index')

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
    crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/navbar.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/base.css') }}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="nav-text navbar-brand" href="{{ url_for('index.index_page') }}">Shediastis</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link nav-text" aria-current="page" href="{{ url_for('index.index_page') }}">Home</a>
              {%if current_page == 'index'%}
                <a class="nav-link nav-text" href="#features">Features</a>
                <a class="nav-link nav-text" href="#about">About</a>
              {%endif%}
              {%if not user%}
                <a class="nav-link nav-text end-item" href="{{ url_for('login.login_page') }}">Login</a>
                <a class="nav-link nav-text end-item" href="{{ url_for('register.registration') }}">Register</a>
              {%else%}
                <a class="nav-link nav-text end-item" href="{{ url_for('login.login_page') }}">Logout</a>
              {%endif%}
            </div>
          </div>
        </div>
    </nav>
    {%with messages = get_flashed_messages(with_categories=true)%}
    {%if messages%}
        {%for category, message in messages%}
            {%if category == 'danger'%}
                <div class="alert alert-danger" role="alert">
                    {{message}}
                </div>
            {%else%}
                <div class="alert alert-success" role="alert">
                    {{message}}
                </div>
        {%endif%}
        {%endfor%}
    {%endif%}
{%endwith%}
    {% block content %}
    {% endblock %}
    <script>
        $('.btn-expand-collapse').click(function(e) {
				$('.navbar-primary').toggleClass('collapsed');
        });
    </script>
</body>
</html>

website/templates/dashboard.html
{% extends 'base.html' %}
{% block title %} Dashboard - {{user.fullname}} {% endblock %}
{% block content %}
<link rel="stylesheet"
href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
crossorigin="anonymous"/>
<link rel="stylesheet" href="{{url_for('static', filename='styles/tasks.css')}}">
<link rel="stylesheet" href="{{url_for('static', filename='styles/dashboard.css')}}">
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div> 
    <div class="wellcome-text"><h1>Welcome Back, <a href="#">{{user.fullname}}</a><div id="MyClockDisplay" class="clock" onload="showTime()"></div></div>
    <div class="container">
        <section class="tasks">
            <header class="tasks-header">
                <h2 class="tasks-title">Tasks</h2>
                <i id="current_task_info_btn" class="fas fa-info-circle"></i>
            </header>
            <fieldset class="tasks-list">
                {%if current_tasks%}
                    {%for task in current_tasks%}
                        <label class="tasks-list-item">
                            <input type="checkbox" name="task_1" value="1" class="tasks-list-cb" onclick="manageTask('{{task.id}}');">
                            <span class="tasks-list-mark"></span>
                            <span class="tasks-list-desc">{{task}}</span>
                        </label>
                    {%endfor%}
                {%else%}
                    <label class="tasks-list-item" style="color: #fff;">
                        No Tasks In This Category
                    </label>
                {%endif%}
            </fieldset>
          </section>

          <!------------------Completedd tasks------------------------>

          <section class="tasks completed">
            <header class="tasks-header">
                <h2 class="tasks-title">Completed Tasks</h2>
                <i id="completed_task_info_btn" class="fas fa-info-circle"></i>
            </header>
            <fieldset class="tasks-list">
                {%if completed_tasks%}
                    {%for task in completed_tasks%}
                        <label class="tasks-list-item">
                            <input type="checkbox" name="task_1" value="1" class="tasks-list-cb" checked onclick="manageTask('{{task.id}}');">
                            <span class="tasks-list-mark"></span>
                            <span class="tasks-list-desc">{{task}}</span>
                        </label>
                    {%endfor%}
                {%else%}
                    <label class="tasks-list-item" style="color: #fff;">
                        No Tasks In This Category
                    </label>
                {%endif%}
            </fieldset>
          </section>
          
          <!------------------------Trashed Tasks--------------------------->

          
          <section class="tasks trashed">
            <header class="tasks-header">
                <h2 class="tasks-title">Trashed Tasks</h2>
                <i id="trashed_task_info_btn" class="fas fa-info-circle"></i>
            </header>
            <fieldset class="tasks-list">
                {%if trashed_tasks%}
                    {%for task in trashed_tasks%}
                        <label class="tasks-list-item">
                            <input type="checkbox" name="task_1" value="1" class="tasks-list-cb" checked onclick="manageTask('{{task.id}}');">
                            <span class="tasks-list-mark"></span>
                            <span class="tasks-list-desc">{{task}}</span>
                        </label>
                    {%endfor%}
                {%else%}
                    <label class="tasks-list-item" style="color: #fff;">
                        No Tasks In This Category
                    </label>
                {%endif%}
            </fieldset>
          </section>
    </div>
    <div id="add-task-group" class="input-group mb-3">
    <input name="task" id="taskDesc" type="text" class="form-control" placeholder="Enter Task" aria-label="Recipient's username" aria-describedby="basic-addon2">
    <span class="input-group-text" id="basic-addon2" onclick="addTask()">Add Task</span>
    </div>
    <div id="current_task_info" class="task-info">
        Click on a task to mark it as completed.
    </div>
    <div id="completed_task_info" class="task-info">
        Click on a completed task to send it in the trash.
    </div>
    <div id="trashed_task_info" class="task-info">
        Click on a completed task to permanently delete it.
    </div>
    <footer style="width: 50%;transform: translate(50%, 50px);text-align: center;color: #3F3D56;">Hover on the info icons of each task to know more about it.</footer>
    <script>
        $('#current_task_info_btn').hover(function(){
            $('#current_task_info').toggle();
        });
        $('#completed_task_info_btn').hover(function(){
            $('#completed_task_info').toggle();
        });
        $('#trashed_task_info_btn').hover(function(){
            $('#trashed_task_info').toggle();
        });
        function manageTask(taskId) {
            fetch('/manage_task/', {
                method : 'POST',
                body : JSON.stringify({taskId : taskId})
            }).then((_res)=>{
                window.location.href = '{{url_for("dashboard.dashboard_page", user=user)}}';
            })
        }
        function addTask() {
            //s$('task')
            var taskDesc = document.getElementById("taskDesc").value;
            console.log(taskDesc);
            fetch('/add_task/', {
                method : 'POST',
                body : JSON.stringify({task : taskDesc})
            }).then((_res)=>{
                window.location.href = '{{url_for("dashboard.dashboard_page", user=user)}}';
            })
        }
        function showTime(){
            var date = new Date();
            var h = date.getHours(); // 0 - 23
            var m = date.getMinutes(); // 0 - 59
            var s = date.getSeconds(); // 0 - 59
            var session = "AM";
            
            if(h == 0){
                h = 12;
            }
            
            if(h > 12){
                h = h - 12;
                session = "PM";
            }
            
            h = (h < 10) ? "0" + h : h;
            m = (m < 10) ? "0" + m : m;
            s = (s < 10) ? "0" + s : s;
            
            var time = h + ":" + m + ":" + s + " " + session;
            document.getElementById("MyClockDisplay").innerText = time;
            document.getElementById("MyClockDisplay").textContent = time;
            
            setTimeout(showTime, 1000);
            
        }
        showTime();
    </script>
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}
{% block title %} Index {% endblock %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/bootstrap.min.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/font-awesome.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/templatemo-art-factory.css')}}">
<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='styles/owl-carousel.css')}}">
    <!-- ***** Welcome Area Start ***** -->
    <div class="welcome-area" id="welcome">

        <!-- ***** Header Text Start ***** -->
        <div class="header-text">
            <div class="container">
                <div class="row">
                    <div class="left-text col-lg-6 col-md-6 col-sm-12 col-xs-12" data-scroll-reveal="enter left move 30px over 0.6s after 0.4s">
                        <h1><strong>Shediastis</strong> is free for YOU</h1>
                        <p>
                            Shediastis is a free to use Daily Life Planner and Organizing application. You can
                            use Shediastis to make your daily life more productive
                            by planning ahed and mapping your day to day activities.
                        </p>
                        <a href="{{url_for('register.registration')}}" class="main-button-slider">Get Started</a>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" data-scroll-reveal="enter right move 30px over 0.6s after 0.4s">
                        <img src="{{url_for('static', filename='images/slider-icon.svg')}}" class="rounded img-fluid d-block mx-auto" alt="First Vector Graphic">
                    </div>
                </div>
            </div>
        </div>
        <!-- ***** Header Text End ***** -->
    </div>
    <!-- ***** Welcome Area End ***** -->


    <!-- ***** Features Big Item Start ***** -->
    <section class="section" id="features">
        <div class="container">
            <div class="row">
                <div class="left-text col-lg-5 col-md-12 col-sm-12 mobile-bottom-fix">
                    <div class="left-heading">
                        <h5>Features</h5>
                    </div>
                    <p>Here are some of the features you can use.</p>
                    <ul>
                        <li>
                            <img class="icon-imgs" src="{{url_for('static', filename='images/event.png')}}" alt="">
                            <div class="text">
                                <h6>Managing Events</h6>
                                <p>You can add certain events to your schedule and mark them as completed or keep them in the trash or completely delete them.</p>
                            </div>
                        </li>
                        <li>
                            <img class="icon-imgs" src="{{url_for('static', filename='images/excercise.png')}}" alt="">
                            <div class="text">
                                <h6>Fitness Organizer</h6>
                                <p>You can create exercise routines and add already existing exircises to them or create and add your own custom exercises.</p>
                            </div>
                        </li>
                        <li>
                            <img class="icon-imgs" src="{{url_for('static', filename='images/reminder.png')}}" alt="">
                            <div class="text">
                                <h6>Reminders</h6>
                                <p>You can set reminders that can be reused and can be set to repeat after certain time spans.</p>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="right-image col-lg-7 col-md-12 col-sm-12 mobile-bottom-fix-big" data-scroll-reveal="enter right move 30px over 0.6s after 0.4s">
                    <img src="{{url_for('static', filename='images/right-image.svg')}}" class="rounded img-fluid d-block mx-auto" alt="App">
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Features Big Item End ***** -->


    <!-- ***** Features Big Item Start ***** -->
    <section class="section" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-12 col-sm-12" data-scroll-reveal="enter left move 30px over 0.6s after 0.4s">
                    <img src="{{url_for('static', filename='images/left-image.svg')}}" class="rounded img-fluid d-block mx-auto" alt="App">
                </div>
                <div class="right-text col-lg-5 col-md-12 col-sm-12 mobile-top-fix">
                    <div class="left-heading">
                        <h5>About</h5>
                    </div>
                    <div class="left-text">
                        <p>This project is developed and in under development by <a href="https://github.com/KawshikBss" target="_blank">Kawshik Biswas</a> as Life planner and organizing application. This project is currently not being developed 
                        commercially and can be considered as the beta version or Version 1.0. You can click the above link or the button below to be reddirected to the developers GitHub profile</p>
                        <a href="https://github.com/KawshikBss" target="_blank" class="main-button">Discover More</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="hr"></div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Features Big Item End ***** -->


   
    <!-- ***** Features Small End ***** -->
    <!-- jQuery -->
    <script src="{{url_for('static', filename='js/jquery-2.1.0.min.js')}}"></script>

    <!-- Bootstrap -->
    <script src="{{url_for('static', filename='js/popper.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>

    <!-- Plugins -->
    <script src="{{url_for('static', filename='js/owl-carousel.js')}}"></script>
    <script src="{{url_for('static', filename='js/scrollreveal.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/waypoints.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/jquery.counterup.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/imgfix.min.js')}}"></script> 
    
    <!-- Global Init -->
    <script src="{{url_for('static', filename='js/custom.js')}}"></script>
{% endblock %}

website/templates/login.html
{%extends 'base.html'%}

{%block title%}Login{%endblock%}

{%block content%}

<link rel="stylesheet" href="{{ url_for('static', filename='styles/register.css') }}">



<div class="container">
	<form method="post" class="col g-3">
        <div class="col-auto form-input">
          <label for="staticEmail2" class="visually-hidden">Email</label>
          <input type="text" class="form-control" name="email" id="email" placeholder="Email">
        </div>
        <div class="col-auto form-input">
          <label for="inputPassword2" class="visually-hidden">Password</label>
          <input type="password" class="form-control" name="password" id="password" placeholder="Password">
        </div>
        <div class="col-auto form-input">
          <button type="submit" class="btn btn-sub mb-3">Login</button>
        </div><div class="col-auto form-input">
          <a class="anchor-link" href="{{ url_for('register.registration') }}">Don't Have an account? Register</a>
        </div>
    </form>
</div>

{%endblock%}

website/templates/register.html
{%extends 'base.html'%}

{%block title%}Register{%endblock%}

{%block content%}

<link rel="stylesheet" href="{{ url_for('static', filename='styles/register.css') }}">

{%with messages = get_flashed_messages(with_categories=true)%}
  {%if messages%}
    {%for category, message in messages%}
      {%if category == 'danger'%}
        <div class="alert alert-danger" role="alert">
          {{message}}
        </div>
      {%else%}
      <div class="alert alert-success" role="alert">
        {{message}}, Click here to <a href="{{ url_for('login.login_page') }}">Login.</a>
      </div>
      {%endif%}
    {%endfor%}
  {%endif%}
{%endwith%}

<div class="container">
    <div class="progress">
        <div class="progress-bar" id="progressbar" role="progressbar" style="width: 0%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
    </div>
	<form method="post" class="col g-3">
        <div class="col-auto form-input">
          <label for="staticEmail2" class="visually-hidden">FirstName</label>
          <input type="text" class="form-control" name="first_name" id="first_name" placeholder="First Name">
        </div>
        <div class="col-auto form-input">
          <label for="staticEmail2" class="visually-hidden">LastName</label>
          <input type="text" class="form-control" name="last_name" id="last_name" placeholder="Last Name">
        </div>
        <div class="col-auto form-input">
          <label for="staticEmail2" class="visually-hidden">Email</label>
          <input type="text" class="form-control" name="email" id="email" placeholder="Email">
        </div>
        <div class="col-auto form-input">
          <label for="inputPassword2" class="visually-hidden">Password</label>
          <input type="password" class="form-control" name="password" id="password" placeholder="Password">
        </div>
        <div class="col-auto form-input">
          <label for="inputPassword2" class="visually-hidden">Confirm Password</label>
          <input type="password" class="form-control" name="confirm_password" id="confirm_password" placeholder="Confirm Password">
        </div>
        <div class="col-auto form-input">
          <button type="submit" class="btn btn-sub mb-3">Register</button>
        </div><div class="col-auto form-input">
          <a class="anchor-link" href="{{ url_for('login.login_page') }}">Already Have an account? Login</a>
        </div>
    </form>
</div>
<script>

  function GetWidthOfProgress(progressbar) {
    var width = ( 100 * parseFloat(progressbar.css('width')) / parseFloat(progressbar.parent().css('width')) );
    return width;
  }

  $(document).ready(function(){

    var progressbar = $('#progressbar')

    var first_name = $('#first_name');
    var last_name = $('#last_name');
    var email = $('#email');
    var password = $('#password');
    var confirm_password = $('#confirm_password');

    first_name.blur(function(e){
      var fname = first_name.val();
      var currWidth = GetWidthOfProgress(progressbar);
      if (fname.length > 1) {
        var targetwidth = currWidth + 20;
        progressbar.css('width', targetwidth + '%');
      }
      else {
        var targetwidth = currWidth - 20;
        progressbar.css('width', targetwidth + '%');
      }
    });
    
    last_name.blur(function(e){
      var lname = last_name.val();
      var currWidth = GetWidthOfProgress(progressbar);
      if (lname.length > 1) {
        var targetwidth = currWidth + 20;
        progressbar.css('width', targetwidth + '%');
      }
      else {
        var targetwidth = currWidth - 20;
        progressbar.css('width', targetwidth + '%');
      }
    });

    email.blur(function(e){
      var mail = first_name.val();
      var currWidth = GetWidthOfProgress(progressbar);
      if (mail.length > 1) {
        var targetwidth = currWidth + 20;
        progressbar.css('width', targetwidth + '%');
      }
      else {
        var targetwidth = currWidth - 20;
        progressbar.css('width', targetwidth + '%');
      }
    });

    password.blur(function(e){
      var pass = first_name.val();
      var currWidth = GetWidthOfProgress(progressbar);
      if (pass.length > 1) {
        var targetwidth = currWidth + 20;
        progressbar.css('width', targetwidth + '%');
      }
      else {
        var targetwidth = currWidth - 20;
        progressbar.css('width', targetwidth + '%');
      }
    });

    confirm_password.blur(function(e){
      var conPass = first_name.val();
      var currWidth = GetWidthOfProgress(progressbar);
      if (conPass.length > 1) {
        var targetwidth = currWidth + 20;
        progressbar.css('width', targetwidth + '%');
      }
      else {
        var targetwidth = currWidth - 20;
        progressbar.css('width', targetwidth + '%');
      }
    });

  })
</script>

{%endblock%}